import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "motion/react";
import { ApiService } from "../api";
import { Project, WorkspaceState } from "../types";
import {
  Folder,
  FolderOpen,
  FileCode,
  Play,
  Terminal,
  MessageSquare,
  Sparkles,
  Layers,
  CheckCircle2,
  Clock,
  AlertOctagon,
  HelpCircle,
  Code,
  BookOpen,
  Settings,
  ChevronRight,
  ChevronDown,
  Plus,
  Send,
  Cpu,
  Database,
  Search,
  Check,
  X,
  Compass,
  FileText,
  Workflow,
  Share2,
  HardDrive,
  Github,
  Monitor,
  Activity,
  Zap,
  Info,
  ExternalLink
} from "lucide-react";

interface WorkspaceViewProps {
  token: string;
  onTabChange: (tab: string) => void;
  showAiPanel?: boolean;
  onToggleAiPanel?: () => void;
}

export default function WorkspaceView({ token, onTabChange, showAiPanel = true, onToggleAiPanel }: WorkspaceViewProps) {
  const [projects, setProjects] = useState<Project[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState<string>("");
  const [activeProject, setActiveProject] = useState<Project | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  // Layout Tab selection in center panel: 'overview' | 'code' | 'docs' | 'tasks' | 'integrations'
  const [activeCenterTab, setActiveCenterTab] = useState<"overview" | "code" | "docs" | "tasks" | "integrations">("overview");

  // Project explorer state
  const [expandedFolders, setExpandedFolders] = useState<Record<string, boolean>>({
    root: true,
    src: true,
    components: true,
    server: true,
    database: true,
  });

  // Code editor states
  const [openFiles, setOpenFiles] = useState<string[]>(["README.md", "src/App.tsx"]);
  const [activeFile, setActiveFile] = useState<string>("src/App.tsx");
  const [codeFiles, setCodeFiles] = useState<Record<string, string>>({
    "src/App.tsx": `import React, { useState } from 'react';\n\nexport default function App() {\n  const [count, setCount] = useState(0);\n  return (\n    <div className="p-8 text-center bg-[#0b0f19] text-white rounded-xl border border-[#1e293b]">\n      <h1 className="text-2xl font-black mb-4">Hello AI Workspace!</h1>\n      <p className="text-sm text-[#94a3b8] mb-6">This component was generated by AI Forge OS.</p>\n      <button \n        onClick={() => setCount(count + 1)} \n        className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg text-xs font-bold transition-all"\n      >\n        Count: {count}\n      </button>\n    </div>\n  );\n}`,
    "README.md": `# Project Developer Workspace\n\nWelcome to your AI Forge workspace. Here you can find code assets, database entities, sitemaps, and test suites compiled directly from your system architecture.\n\n### Tech Stack Selection\n- **Frontend**: React, Vite, Tailwind CSS\n- **Backend**: Node.js, Express\n- **Database**: PostgreSQL / Drizzle ORM\n\n### Running Dev Environment\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\``,
    "server/routes.ts": `import { Router } from "express";\nconst router = Router();\n\nrouter.get("/api/health", (req, res) => {\n  res.json({ status: "healthy", service: "AI Forge Engine" });\n});\n\nexport default router;`,
    "database/schema.ts": `import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";\n\nexport const usersTable = pgTable("users", {\n  id: serial("id").primaryKey(),\n  name: text("name").notNull(),\n  email: text("email").notNull().unique(),\n  createdAt: timestamp("created_at").defaultNow(),\n});`,
    "Dockerfile": `FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\nEXPOSE 3000\nCMD ["npm", "run", "start"]`
  });

  // AI Chat states
  const [chatInput, setChatInput] = useState("");
  const [chatMessages, setChatMessages] = useState<{ role: "user" | "assistant"; content: string; timestamp: string }[]>([
    {
      role: "assistant",
      content: "Hello! I am your CTO Architect Assistant. I am fully synchronized with this project's specification, database schema, and technical stack blueprint. What would you like to develop or review today?",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  const [isAiTyping, setIsAiTyping] = useState(false);

  // Task lists
  const [selectedSprint, setSelectedSprint] = useState<string>("Sprint 1");
  const [taskStatuses, setTaskStatuses] = useState<Record<string, "Todo" | "In Progress" | "Blocked" | "Complete">>({});

  // Command palette state
  const [showCommandPalette, setShowCommandPalette] = useState(false);
  const [cmdSearchQuery, setCmdSearchQuery] = useState("");

  // Recent actions logs
  const [workspaceHistory, setWorkspaceHistory] = useState<{ action: string; timestamp: string }[]>([
    { action: "Workspace initialized successfully", timestamp: new Date().toLocaleTimeString() }
  ]);

  const chatBottomRef = useRef<HTMLDivElement | null>(null);

  // Load projects list
  useEffect(() => {
    loadProjects();
  }, []);

  // Listen for Ctrl+K command palette
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "k") {
        e.preventDefault();
        setShowCommandPalette((prev) => !prev);
      } else if (e.key === "Escape") {
        setShowCommandPalette(false);
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Scroll chat bottom
  useEffect(() => {
    chatBottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages, isAiTyping]);

  const loadProjects = async (selectId?: string) => {
    setIsLoading(true);
    try {
      const list = await ApiService.listProjects(token);
      setProjects(list);
      if (list.length > 0) {
        const idToSelect = selectId || list[0].id;
        setSelectedProjectId(idToSelect);
        const proj = list.find((p) => p.id === idToSelect);
        if (proj) {
          loadProjectWorkspace(proj);
        }
      }
    } catch (e) {
      console.error("Failed to load workspace projects list", e);
    } finally {
      setIsLoading(false);
    }
  };

  const loadProjectWorkspace = (project: Project) => {
    setActiveProject(project);

    // Read stored workspace state
    if (project.workspace) {
      const ws = project.workspace;
      if (ws.aiConversations && ws.aiConversations.length > 0) {
        setChatMessages(ws.aiConversations);
      } else {
        setChatMessages([
          {
            role: "assistant",
            content: `Welcome back to the workspace for **${project.name}**. I am fully synced with your custom technical stack (${project.blueprint?.techStack?.frontend || "React"}, ${project.blueprint?.techStack?.backend || "Express"}) and database blueprint. Let me know what system component or route we should build next!`,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
          }
        ]);
      }

      if (ws.codeFiles) {
        setCodeFiles(ws.codeFiles);
      } else {
        generateDefaultFiles(project);
      }

      if (ws.openFiles) setOpenFiles(ws.openFiles);
      if (ws.activeFile) setActiveFile(ws.activeFile);
      if (ws.currentSprint) setSelectedSprint(ws.currentSprint);
      if (ws.taskStatuses) setTaskStatuses(ws.taskStatuses);
      if (ws.workspaceHistory) setWorkspaceHistory(ws.workspaceHistory);
    } else {
      // Default initial states based on project parameters
      generateDefaultFiles(project);
      setChatMessages([
        {
          role: "assistant",
          content: `Welcome to the active AI Workspace for **${project.name}**! Here you have a persistent CTO Assistant, project explorer, and real-time code sandbox. Ready to compose your services.`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
      setOpenFiles(["README.md", "src/App.tsx"]);
      setActiveFile("src/App.tsx");
      setWorkspaceHistory([{ action: "Developer workspace loaded first time", timestamp: new Date().toLocaleTimeString() }]);
      
      // Seed default task statuses
      const seedStatuses: Record<string, "Todo" | "In Progress" | "Blocked" | "Complete"> = {};
      if (project.blueprint?.sprintPlan) {
        project.blueprint.sprintPlan.forEach((sprint) => {
          sprint.objectives.forEach((obj) => {
            seedStatuses[obj] = "Todo";
          });
        });
      }
      setTaskStatuses(seedStatuses);
    }
  };

  const generateDefaultFiles = (project: Project) => {
    const tech = project.blueprint?.techStack;
    const dbDesign = project.blueprint?.databaseDesign;
    const apiPlan = project.blueprint?.restApiPlan;

    const schemaFields = dbDesign?.entities?.[0]?.fields.join("\n  ") || "id: serial('id').primaryKey()";
    const routeExamples = apiPlan?.map(r => `// ${r.method} ${r.endpoint}\nrouter.${r.method.toLowerCase()}("${r.endpoint.replace('/api', '')}", (req, res) => {\n  res.json({ message: "${r.description}" });\n});`).join("\n\n") || `router.get("/status", (req, res) => {\n  res.json({ status: "ok" });\n});`;

    const defaultFiles: Record<string, string> = {
      "README.md": `# ${project.name} Documentation\n\n${project.description}\n\n## 🛠️ Technical Stack Selection\n- **Frontend Library**: ${tech?.frontend || "React, Vite, Tailwind CSS"}\n- **Backend Services**: ${tech?.backend || "Node.js, Express"}\n- **Database Ingress**: ${tech?.database || "PostgreSQL, Drizzle ORM"}\n- **Cloud Deployment**: ${tech?.cloudHosting || "Google Cloud Run"}\n- **CI/CD Pipeline**: ${tech?.devops || "GitHub Actions & Docker"}\n\n## 🚀 Quick Start Guide\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\``,
      "src/App.tsx": `import React from 'react';\n\nexport default function App() {\n  return (\n    <div className="min-h-screen bg-[#0b0f19] text-slate-100 flex flex-col justify-center items-center p-8 font-sans">\n      <div className="max-w-xl bg-[#141b2d]/60 border border-[#1e293b] p-6 rounded-2xl shadow-xl">\n        <h1 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-[#10b981] mb-2">\n          ${project.name}\n        </h1>\n        <p className="text-xs text-slate-400 mb-6">${project.description}</p>\n        <div className="p-4 bg-[#0b0f19] border border-[#1e293b]/80 rounded-xl">\n          <span className="text-[10px] uppercase font-bold text-blue-400">Environment</span>\n          <p className="text-xs font-mono text-[#10b981] mt-1">✔ Local development server listening on port 3000</p>\n        </div>\n      </div>\n    </div>\n  );\n}`,
      "server/server.ts": `import express from "express";\nimport router from "./routes";\n\nconst app = express();\nconst PORT = process.env.PORT || 3000;\n\napp.use(express.json());\napp.use(router);\n\napp.listen(PORT, () => {\n  console.log("Server listening at http://localhost:" + PORT);\n});`,
      "server/routes.ts": `import { Router } from "express";\nconst router = Router();\n\n${routeExamples}\n\nexport default router;`,
      "database/schema.ts": `import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";\n\nexport const ${dbDesign?.entities?.[0]?.name || "items"}Table = pgTable("${(dbDesign?.entities?.[0]?.name || "items").toLowerCase()}", {\n  ${schemaFields}\n});`,
      "Dockerfile": `FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\nEXPOSE 3000\nCMD ["node", "dist/server.js"]`
    };

    setCodeFiles(defaultFiles);
  };

  const handleProjectSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value;
    setSelectedProjectId(val);
    const proj = projects.find((p) => p.id === val);
    if (proj) {
      loadProjectWorkspace(proj);
    }
  };

  // Persists current local states to Project Workspace database memory
  const persistWorkspaceToBackend = async (
    customMessages?: typeof chatMessages,
    customFiles?: Record<string, string>,
    customOpen?: string[],
    customActive?: string,
    customStatuses?: Record<string, "Todo" | "In Progress" | "Blocked" | "Complete">,
    customHistory?: typeof workspaceHistory
  ) => {
    if (!selectedProjectId) return;
    try {
      const stateObj: WorkspaceState = {
        aiConversations: customMessages || chatMessages,
        codeFiles: customFiles || codeFiles,
        openFiles: customOpen || openFiles,
        activeFile: customActive || activeFile,
        currentSprint: selectedSprint,
        taskStatuses: customStatuses || taskStatuses,
        workspaceHistory: customHistory || workspaceHistory
      };
      await ApiService.saveWorkspace(selectedProjectId, stateObj, token);
    } catch (e) {
      console.error("Workspace autosave fail", e);
    }
  };

  const handleOpenFile = (filePath: string) => {
    if (!openFiles.includes(filePath)) {
      const updated = [...openFiles, filePath];
      setOpenFiles(updated);
      persistWorkspaceToBackend(undefined, undefined, updated, filePath);
    }
    setActiveFile(filePath);
    setActiveCenterTab("code");
    logHistory(`Opened file "${filePath}" in workspace editor`);
  };

  const handleCloseFile = (filePath: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const filtered = openFiles.filter((f) => f !== filePath);
    setOpenFiles(filtered);
    let nextActive = activeFile;
    if (activeFile === filePath && filtered.length > 0) {
      nextActive = filtered[filtered.length - 1];
      setActiveFile(nextActive);
    }
    persistWorkspaceToBackend(undefined, undefined, filtered, nextActive);
  };

  const handleCodeChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newVal = e.target.value;
    const updatedFiles = { ...codeFiles, [activeFile]: newVal };
    setCodeFiles(updatedFiles);
    persistWorkspaceToBackend(undefined, updatedFiles);
  };

  const logHistory = (action: string) => {
    const entry = { action, timestamp: new Date().toLocaleTimeString() };
    const updated = [entry, ...workspaceHistory].slice(0, 30);
    setWorkspaceHistory(updated);
    persistWorkspaceToBackend(undefined, undefined, undefined, undefined, undefined, updated);
  };

  const handleSendChatMessage = async (msg?: string) => {
    const content = msg || chatInput;
    if (!content.trim() || !selectedProjectId) return;

    const userMsg = {
      role: "user" as const,
      content,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    const newMessages = [...chatMessages, userMsg];
    setChatMessages(newMessages);
    setChatInput("");
    setIsAiTyping(true);

    logHistory(`Asked Assistant: "${content.substring(0, 40)}${content.length > 40 ? "..." : ""}"`);

    try {
      // Execute context-aware chat via back-end GeminiService
      const payload = {
        message: content,
        history: chatMessages.map((m) => ({ role: m.role, content: m.content }))
      };
      const response = await ApiService.workspaceChat(selectedProjectId, payload, token);
      
      const assistantMsg = {
        role: "assistant" as const,
        content: response.reply,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      const finalMessages = [...newMessages, assistantMsg];
      setChatMessages(finalMessages);
      setIsAiTyping(false);
      persistWorkspaceToBackend(finalMessages);
    } catch (e: any) {
      console.error(e);
      const errorMsg = {
        role: "assistant" as const,
        content: `Error contacting compiler brain: ${e.message || e}. Using deterministic fallback compilation guidelines instead.`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      const finalMessages = [...newMessages, errorMsg];
      setChatMessages(finalMessages);
      setIsAiTyping(false);
      persistWorkspaceToBackend(finalMessages);
    }
  };

  const handleQuickAction = async (action: string) => {
    setIsAiTyping(true);
    logHistory(`Triggered Quick Action: "${action}"`);
    
    // Auto-create a user notification message in chat representing the quick action
    const userMsg = {
      role: "user" as const,
      content: `[Quick Action] Please execute: "${action}" for my project "${activeProject?.name}".`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    const newMessages = [...chatMessages, userMsg];
    setChatMessages(newMessages);

    try {
      const payload = {
        message: `Please generate the code or guidelines for this quick action: ${action}`,
        history: chatMessages.map((m) => ({ role: m.role, content: m.content })),
        quickAction: action
      };
      const response = await ApiService.workspaceChat(selectedProjectId, payload, token);

      const assistantMsg = {
        role: "assistant" as const,
        content: response.reply,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      const finalMessages = [...newMessages, assistantMsg];
      setChatMessages(finalMessages);
      setIsAiTyping(false);

      // If AI generated a clear block of code, let's offer to write it into active tab file or add a virtual file!
      const codeBlockRegex = /```(?:typescript|javascript|tsx|json|css|html|sql|bash)?\s*([\s\S]*?)```/g;
      const matches = [...assistantMsg.content.matchAll(codeBlockRegex)];
      if (matches.length > 0 && activeFile) {
        // We found code blocks in response! That's awesome
        const codeOnly = matches[0][1];
        // Offer to write directly
        logHistory(`AI Architect generated a system blueprint code module for "${activeFile}"`);
      }

      persistWorkspaceToBackend(finalMessages);
    } catch (e: any) {
      console.error(e);
      setIsAiTyping(false);
    }
  };

  const handleTaskStatusChange = (taskObj: string, newStatus: "Todo" | "In Progress" | "Blocked" | "Complete") => {
    const updated = { ...taskStatuses, [taskObj]: newStatus };
    setTaskStatuses(updated);
    logHistory(`Updated task "${taskObj.substring(0, 25)}..." status to [${newStatus}]`);
    persistWorkspaceToBackend(undefined, undefined, undefined, undefined, updated);
  };

  const toggleFolder = (folderName: string) => {
    setExpandedFolders((prev) => ({ ...prev, [folderName]: !prev[folderName] }));
  };

  // Helper: render beautiful structured markdown inline
  const renderMarkdown = (text: string) => {
    if (!text) return null;
    const lines = text.split("\n");
    let inCodeBlock = false;
    let codeBlockContent: string[] = [];

    return lines.map((line, idx) => {
      if (line.startsWith("```")) {
        if (inCodeBlock) {
          inCodeBlock = false;
          const content = codeBlockContent.join("\n");
          codeBlockContent = [];
          return (
            <pre key={idx} className="p-4 bg-[#080c14] border border-[#1e293b] rounded-lg text-xs font-mono text-[#10b981] overflow-x-auto my-3 leading-relaxed relative">
              <button 
                onClick={() => {
                  navigator.clipboard.writeText(content);
                  logHistory("Copied code block to clipboard");
                }}
                className="absolute top-2 right-2 px-1.5 py-0.5 bg-[#141b2d] border border-[#1e293b] rounded text-[9px] text-[#94a3b8] hover:text-white"
              >
                Copy
              </button>
              <code>{content}</code>
            </pre>
          );
        } else {
          inCodeBlock = true;
          return null;
        }
      }

      if (inCodeBlock) {
        codeBlockContent.push(line);
        return null;
      }

      if (line.startsWith("# ")) {
        return <h1 key={idx} className="text-xl font-black text-white mt-5 mb-2.5 pb-1 border-b border-[#1e293b]">{line.replace("# ", "")}</h1>;
      }
      if (line.startsWith("## ")) {
        return <h2 key={idx} className="text-lg font-bold text-white mt-4 mb-2">{line.replace("## ", "")}</h2>;
      }
      if (line.startsWith("### ")) {
        return <h3 key={idx} className="text-base font-semibold text-blue-400 mt-3 mb-1.5">{line.replace("### ", "")}</h3>;
      }
      if (line.startsWith("- ") || line.startsWith("* ")) {
        return (
          <li key={idx} className="text-xs text-[#94a3b8] ml-4 list-disc mb-1 leading-relaxed">
            {line.substring(2)}
          </li>
        );
      }
      if (line.startsWith("> ")) {
        return (
          <div key={idx} className="pl-3.5 border-l-2 border-blue-500 text-xs italic text-slate-400 my-2">
            {line.replace("> ", "")}
          </div>
        );
      }

      return line.trim() ? (
        <p key={idx} className="text-xs text-[#94a3b8] leading-relaxed mb-2">{line}</p>
      ) : <div key={idx} className="h-2" />;
    });
  };

  // Calculate project completion percent
  const getProjectCompletionPercent = () => {
    if (!activeProject || !activeProject.blueprint?.sprintPlan) return 15;
    const allTasks = activeProject.blueprint.sprintPlan.flatMap(s => s.objectives);
    if (allTasks.length === 0) return 15;
    const completedCount = allTasks.filter(t => taskStatuses[t] === "Complete").length;
    const inProgressCount = allTasks.filter(t => taskStatuses[t] === "In Progress").length;
    const weight = (completedCount * 1.0 + inProgressCount * 0.4) / allTasks.length;
    return Math.min(100, Math.round(15 + weight * 85));
  };

  // Command palette executions
  const executeCommand = (cmd: string) => {
    setShowCommandPalette(false);
    logHistory(`Executed shortcut command: "${cmd}"`);
    
    switch (cmd) {
      case "Create component":
        setActiveFile("src/components/NewComponent.tsx");
        setCodeFiles({
          ...codeFiles,
          "src/components/NewComponent.tsx": `import React from 'react';\n\nexport default function NewComponent() {\n  return (\n    <div className="p-4 border border-dashed border-[#1e293b] rounded-xl bg-[#141b2d]/40">\n      <p className="text-xs text-slate-400">Custom component created via Command Palette</p>\n    </div>\n  );\n}`
        });
        if (!openFiles.includes("src/components/NewComponent.tsx")) {
          setOpenFiles([...openFiles, "src/components/NewComponent.tsx"]);
        }
        setActiveCenterTab("code");
        break;
      case "Generate API":
        handleQuickAction("Generate API");
        break;
      case "Open Settings":
        onTabChange("settings");
        break;
      case "Open Forge Brain":
        onTabChange("forge_brain");
        break;
      case "Open Workspace":
        setActiveCenterTab("overview");
        break;
      case "Generate tests":
        handleQuickAction("Generate Tests");
        break;
      case "Deploy":
        setActiveCenterTab("integrations");
        break;
      default:
        break;
    }
  };

  const commandList = [
    { name: "Create component", desc: "Instantiate a new reusable React component", shortcut: "Ctrl+C" },
    { name: "Generate page", desc: "Build a brand new structural layout screen template", shortcut: "Ctrl+P" },
    { name: "Generate API", desc: "Compile a secure REST gateway endpoint in express", shortcut: "Ctrl+A" },
    { name: "Open Settings", desc: "View global configurations and system secrets", shortcut: "G+S" },
    { name: "Open Forge Brain", desc: "Review compiled technical solutions blueprint", shortcut: "G+B" },
    { name: "Open Workspace", desc: "Go to central system activity summary", shortcut: "G+W" },
    { name: "Generate tests", desc: "Produce functional unit suites", shortcut: "Ctrl+T" },
    { name: "Deploy", desc: "Review cloud targets and pipeline variables", shortcut: "Ctrl+D" },
  ];

  const filteredCommands = commandList.filter(c => 
    c.name.toLowerCase().includes(cmdSearchQuery.toLowerCase()) || 
    c.desc.toLowerCase().includes(cmdSearchQuery.toLowerCase())
  );

  return (
    <div className="max-w-7xl mx-auto px-4 md:px-6 py-6 text-left font-sans flex flex-col h-[calc(100vh-80px)] overflow-hidden">
      
      {/* Dynamic Header Toolbar */}
      <div className="mb-4 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 border-b border-[#141b2d] pb-4 shrink-0">
        <div>
          <h1 className="text-2xl font-black text-white flex items-center gap-2">
            <Code className="w-6.5 h-6.5 text-blue-500" />
            Developer Workspace
          </h1>
          <p className="text-[10px] text-[#94a3b8] mt-0.5">
            Press <kbd className="px-1.5 py-0.5 bg-[#141b2d] border border-[#1e293b] rounded text-[9px] font-mono text-[#3b82f6]">Ctrl+K</kbd> to open Command Palette
          </p>
        </div>

        {/* Project Context selector */}
        <div className="flex items-center gap-3 w-full sm:w-auto">
          <label className="text-[10px] font-bold uppercase text-[#475569] whitespace-nowrap">Active Workspace</label>
          <select
            value={selectedProjectId}
            onChange={handleProjectSelect}
            className="px-3.5 py-1.5 bg-[#141b2d] border border-[#1e293b] rounded-lg text-xs text-white focus:outline-none focus:border-[#3b82f6] min-w-[180px]"
          >
            {projects.map((p) => (
              <option key={p.id} value={p.id}>
                📁 {p.name}
              </option>
            ))}
          </select>
        </div>
      </div>

      {isLoading ? (
        <div className="flex-1 flex flex-col items-center justify-center text-slate-400">
          <Cpu className="w-10 h-10 animate-spin text-blue-500 mb-4" />
          <p className="text-xs font-semibold">Synchronizing Project Space Modules...</p>
        </div>
      ) : !activeProject ? (
        <div className="flex-1 flex flex-col items-center justify-center text-slate-400 border border-dashed border-[#1e293b] rounded-2xl p-12 bg-[#141b2d]/10">
          <Zap className="w-12 h-12 text-[#475569] mb-4" />
          <h3 className="text-sm font-bold text-white">No active launchpad project detected</h3>
          <p className="text-xs text-[#94a3b8] max-w-sm text-center mt-1">First compile a system blueprint in the 🧠 Forge Brain view to initialize your developer workspace.</p>
          <button 
            onClick={() => onTabChange("forge_brain")}
            className="mt-6 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-bold transition-all"
          >
            Create Blueprint
          </button>
        </div>
      ) : (
        <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-5 h-full overflow-hidden pb-4">
          
          {/* ========================================== */}
          {/* LEFT PANEL: PROJECT EXPLORER (3 cols)      */}
          {/* ========================================== */}
          <div className="lg:col-span-3 bg-[#0e1424]/75 border border-[#1e293b] rounded-xl flex flex-col h-full overflow-hidden shadow-xl backdrop-blur-md">
            <div className="p-3 bg-[#11192a] border-b border-[#1e293b] flex justify-between items-center shrink-0">
              <span className="text-[10px] font-black uppercase tracking-wider text-[#94a3b8] flex items-center gap-1.5">
                <HardDrive className="w-3.5 h-3.5 text-blue-400" />
                Project Explorer
              </span>
              <span className="text-[9px] bg-blue-950/40 text-blue-400 border border-blue-900/60 px-1.5 py-0.5 rounded font-extrabold uppercase">
                Active
              </span>
            </div>

            {/* Tree menu body */}
            <div className="flex-1 overflow-y-auto p-3.5 space-y-4 custom-scrollbar text-xs">
              
              {/* Folder: Architecture Specifications */}
              <div>
                <button 
                  onClick={() => toggleFolder("root")} 
                  className="w-full flex items-center justify-between py-1 text-slate-300 hover:text-white font-semibold"
                >
                  <span className="flex items-center gap-1.5">
                    {expandedFolders.root ? <FolderOpen className="w-3.5 h-3.5 text-yellow-500 shrink-0" /> : <Folder className="w-3.5 h-3.5 text-yellow-500 shrink-0" />}
                    Workspace Files
                  </span>
                  {expandedFolders.root ? <ChevronDown className="w-3 h-3 text-slate-500" /> : <ChevronRight className="w-3 h-3 text-slate-500" />}
                </button>
                
                {expandedFolders.root && (
                  <div className="pl-4 border-l border-[#1e293b]/60 ml-2 mt-1 space-y-1">
                    {Object.keys(codeFiles).map((f) => (
                      <button
                        key={f}
                        onClick={() => handleOpenFile(f)}
                        className={`w-full flex items-center gap-1.5 py-1 px-1.5 rounded text-left transition-colors ${
                          activeFile === f && activeCenterTab === "code"
                            ? "bg-blue-950/40 text-blue-400 font-medium"
                            : "text-[#94a3b8] hover:text-white hover:bg-[#141b2d]/40"
                        }`}
                      >
                        <FileCode className="w-3.5 h-3.5 shrink-0" />
                        <span className="truncate">{f}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* Blueprint Summary Nodes */}
              {activeProject.blueprint && (
                <div className="space-y-1.5 pt-2 border-t border-[#1e293b]/40">
                  <span className="text-[9px] uppercase font-black text-[#475569] tracking-wider block mb-1">Architecture Schemas</span>
                  
                  {/* Database nodes */}
                  <div>
                    <button 
                      onClick={() => toggleFolder("database")}
                      className="w-full flex items-center justify-between py-1 text-slate-300 hover:text-white"
                    >
                      <span className="flex items-center gap-1.5">
                        <Database className="w-3.5 h-3.5 text-amber-500 shrink-0" />
                        Database Tables
                      </span>
                      {expandedFolders.database ? <ChevronDown className="w-3 h-3 text-slate-500" /> : <ChevronRight className="w-3 h-3 text-slate-500" />}
                    </button>
                    {expandedFolders.database && (
                      <div className="pl-4 ml-2 mt-0.5 space-y-1 border-l border-[#1e293b]/40">
                        {activeProject.blueprint.databaseDesign.entities.map((e, idx) => (
                          <div key={idx} className="py-0.5 text-[#94a3b8] flex items-center gap-1 text-[11px]">
                            <span className="text-[#475569]">⚡</span> {e.name}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* REST APIs */}
                  <div className="pt-1">
                    <button 
                      onClick={() => toggleFolder("server")}
                      className="w-full flex items-center justify-between py-1 text-slate-300 hover:text-white"
                    >
                      <span className="flex items-center gap-1.5">
                        <Zap className="w-3.5 h-3.5 text-red-400 shrink-0" />
                        REST API Gateways
                      </span>
                      {expandedFolders.server ? <ChevronDown className="w-3 h-3 text-slate-500" /> : <ChevronRight className="w-3 h-3 text-slate-500" />}
                    </button>
                    {expandedFolders.server && (
                      <div className="pl-4 ml-2 mt-0.5 space-y-1 border-l border-[#1e293b]/40 max-h-32 overflow-y-auto">
                        {activeProject.blueprint.restApiPlan.map((r, idx) => (
                          <div key={idx} className="py-0.5 text-[10px] font-mono text-slate-300 truncate">
                            <span className="text-emerald-400 font-extrabold mr-1">{r.method}</span> {r.endpoint}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Sprints checklist navigation */}
              {activeProject.blueprint?.sprintPlan && (
                <div className="pt-2 border-t border-[#1e293b]/40">
                  <span className="text-[9px] uppercase font-black text-[#475569] tracking-wider block mb-1">Roadmap Timeline</span>
                  <div className="space-y-1">
                    {activeProject.blueprint.sprintPlan.map((sprint, idx) => {
                      const isSel = selectedSprint === sprint.name;
                      return (
                        <button
                          key={idx}
                          onClick={() => {
                            setSelectedSprint(sprint.name);
                            setActiveCenterTab("tasks");
                            logHistory(`Selected roadmap focus: "${sprint.name}"`);
                          }}
                          className={`w-full text-left py-1 px-1.5 rounded transition-all text-[11px] flex items-center justify-between ${
                            isSel && activeCenterTab === "tasks"
                              ? "bg-blue-950/30 text-blue-400 border-l-2 border-blue-500"
                              : "text-[#94a3b8] hover:text-white"
                          }`}
                        >
                          <span className="truncate">📅 {sprint.name}</span>
                          <span className="text-[9px] text-[#475569]">{sprint.duration}</span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Static Assets nodes */}
              <div className="pt-2 border-t border-[#1e293b]/40">
                <span className="text-[9px] uppercase font-black text-[#475569] tracking-wider block mb-1.5">Deployments</span>
                <button
                  onClick={() => setActiveCenterTab("integrations")}
                  className={`w-full text-left py-1 px-1.5 rounded transition-all text-[11px] flex items-center gap-1.5 ${
                    activeCenterTab === "integrations" ? "bg-purple-950/20 text-purple-400 border-l-2 border-purple-500" : "text-[#94a3b8] hover:text-white"
                  }`}
                >
                  <Workflow className="w-3.5 h-3.5" />
                  Integration Pipeline
                </button>
              </div>

            </div>
          </div>

          {/* ========================================== */}
          {/* CENTER PANEL: WORKSPACE PANEL (5 cols)     */}
          {/* ========================================== */}
          <div className={`${showAiPanel ? "lg:col-span-5" : "lg:col-span-9"} flex flex-col h-full bg-[#141b2d]/30 border border-[#1e293b] rounded-xl overflow-hidden shadow-2xl relative`}>
            
            {/* CENTRAL TABS */}
            <div className="flex border-b border-[#1e293b] bg-[#0e1424] overflow-x-auto shrink-0 scrollbar-none">
              {[
                { id: "overview", label: "Overview", icon: Compass },
                { id: "code", label: "Sandbox IDE", icon: Code },
                { id: "docs", label: "Docs Guide", icon: BookOpen },
                { id: "tasks", label: "Roadmap Tasks", icon: CheckCircle2 },
                { id: "integrations", label: "Integration", icon: Workflow },
              ].map((tab) => {
                const isSel = activeCenterTab === tab.id;
                return (
                  <button
                    key={tab.id}
                    onClick={() => {
                      setActiveCenterTab(tab.id as any);
                      logHistory(`Viewed Tab "${tab.label}"`);
                    }}
                    className={`px-4 py-3 text-xs font-semibold flex items-center gap-1.5 border-b-2 transition-all shrink-0 ${
                      isSel
                        ? "border-blue-500 bg-[#141b2d]/40 text-white"
                        : "border-transparent text-[#94a3b8] hover:text-white hover:bg-[#141b2d]/25"
                    }`}
                  >
                    <tab.icon className="w-3.5 h-3.5" />
                    {tab.label}
                  </button>
                );
              })}
            </div>

            {/* TAB BODY WORKSPACE */}
            <div className="flex-1 overflow-y-auto p-4 custom-scrollbar text-xs">
              
              {/* TAB 1: OVERVIEW */}
              {activeCenterTab === "overview" && (
                <div className="space-y-5">
                  <div className="p-4 rounded-xl bg-gradient-to-br from-blue-950/20 to-indigo-950/25 border border-blue-900/40 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-blue-500/5 blur-xl rounded-full" />
                    <h3 className="text-sm font-black text-white">{activeProject.name}</h3>
                    <p className="text-xs text-[#94a3b8] mt-1 leading-relaxed">{activeProject.description}</p>
                    
                    {/* Completion score indicator */}
                    <div className="mt-5">
                      <div className="flex justify-between items-center mb-1.5 text-[10px] font-bold text-[#475569] uppercase">
                        <span>Workspace Readiness Progress</span>
                        <span className="text-blue-400 font-extrabold">{getProjectCompletionPercent()}%</span>
                      </div>
                      <div className="w-full bg-[#0b0f19] h-2 rounded-full overflow-hidden border border-[#1e293b]">
                        <div 
                          className="bg-gradient-to-r from-blue-500 to-[#10b981] h-full rounded-full transition-all duration-500"
                          style={{ width: `${getProjectCompletionPercent()}%` }}
                        />
                      </div>
                    </div>
                  </div>

                  {/* Sprints status quick metrics */}
                  <div className="grid grid-cols-2 gap-3">
                    <div className="p-3 bg-[#11192a]/55 border border-[#1e293b]/70 rounded-lg">
                      <span className="text-[9px] uppercase font-black text-[#475569] block mb-1">Focus Schedule</span>
                      <p className="text-xs font-bold text-white flex items-center gap-1.5">
                        <Clock className="w-3.5 h-3.5 text-blue-400" />
                        {selectedSprint}
                      </p>
                    </div>
                    <div className="p-3 bg-[#11192a]/55 border border-[#1e293b]/70 rounded-lg">
                      <span className="text-[9px] uppercase font-black text-[#475569] block mb-1">Project Category</span>
                      <p className="text-xs font-bold text-white truncate">
                        🏷️ {activeProject.category || "SaaS System"}
                      </p>
                    </div>
                  </div>

                  {/* Activity Log trails */}
                  <div className="space-y-2">
                    <h4 className="text-xs font-bold text-white flex items-center gap-1.5 border-b border-[#1e293b] pb-2">
                      <Activity className="w-3.5 h-3.5 text-emerald-400" />
                      Live Action History logs
                    </h4>
                    <div className="space-y-2 max-h-52 overflow-y-auto pr-1">
                      {workspaceHistory.map((log, i) => (
                        <div key={i} className="p-2.5 bg-[#141b2d]/30 border border-[#1e293b]/50 rounded flex justify-between items-center text-[11px] hover:bg-[#141b2d]/40 transition-colors">
                          <span className="text-slate-300 truncate pr-2">🛠️ {log.action}</span>
                          <span className="text-[9px] text-[#475569] shrink-0">{log.timestamp}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 2: CODE SANDBOX IDE */}
              {activeCenterTab === "code" && (
                <div className="flex flex-col h-full overflow-hidden">
                  
                  {/* File tabs pills */}
                  <div className="flex gap-1.5 overflow-x-auto pb-2 border-b border-[#1e293b] shrink-0">
                    {openFiles.map((file) => {
                      const isActive = activeFile === file;
                      return (
                        <div
                          key={file}
                          onClick={() => setActiveFile(file)}
                          className={`px-2.5 py-1 rounded text-[11px] font-medium flex items-center gap-1.5 cursor-pointer transition-colors ${
                            isActive
                              ? "bg-blue-600 text-white"
                              : "bg-[#0e1424] text-[#94a3b8] hover:text-white"
                          }`}
                        >
                          <FileCode className="w-3 h-3" />
                          <span>{file.split("/").pop()}</span>
                          <button
                            onClick={(e) => handleCloseFile(file, e)}
                            className="hover:text-red-400 text-[10px]"
                          >
                            &times;
                          </button>
                        </div>
                      );
                    })}
                  </div>

                  {/* Sandbox Monaco Lookalike editor */}
                  <div className="flex-1 mt-3 flex flex-col overflow-hidden bg-[#080c14] border border-[#1e293b] rounded-xl relative">
                    <div className="p-2 bg-[#0d1322] border-b border-[#1e293b] flex justify-between items-center text-[10px] text-[#475569] font-mono">
                      <span>{activeFile}</span>
                      <span className="text-emerald-500 animate-pulse flex items-center gap-1">
                        <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full" />
                        Autosaved
                      </span>
                    </div>

                    <div className="flex-1 flex overflow-hidden font-mono text-[11px]">
                      {/* Gutter Line numbers */}
                      <div className="w-8 bg-[#0a0f1d] text-[#475569] text-right pr-2 py-3 select-none leading-relaxed border-r border-[#1e293b]/40">
                        {Array.from({ length: Math.max(12, (codeFiles[activeFile] || "").split("\n").length) }).map((_, i) => (
                          <div key={i}>{i + 1}</div>
                        ))}
                      </div>

                      {/* Text editor area */}
                      <textarea
                        value={codeFiles[activeFile] || ""}
                        onChange={handleCodeChange}
                        className="flex-1 bg-transparent text-slate-100 p-3 outline-none resize-none overflow-auto leading-relaxed border-none focus:ring-0 custom-scrollbar"
                        placeholder="// Type code here..."
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 3: DOCUMENTATION */}
              {activeCenterTab === "docs" && (
                <div className="prose prose-invert max-w-none">
                  <div className="p-4 bg-[#11192a]/55 border border-[#1e293b]/70 rounded-xl mb-4">
                    <h3 className="text-xs font-black text-white flex items-center gap-1.5 mb-2">
                      <BookOpen className="w-4 h-4 text-blue-400" />
                      Compiled Project Guide documentation
                    </h3>
                    <p className="text-[11px] text-[#94a3b8] leading-relaxed">This guide is dynamic, constructed explicitly based on the technological blueprints compiled during the Forge Brain configuration step.</p>
                  </div>
                  <div className="bg-[#0e1424]/40 p-4 border border-[#1e293b] rounded-xl">
                    {renderMarkdown(codeFiles["README.md"] || "# Workspace documentation not loaded")}
                  </div>
                </div>
              )}

              {/* TAB 4: TASKS ROADMAP */}
              {activeCenterTab === "tasks" && (
                <div className="space-y-4">
                  <div className="p-4 bg-[#11192a]/55 border border-[#1e293b] rounded-xl flex justify-between items-center">
                    <div>
                      <h3 className="text-xs font-bold text-white flex items-center gap-1.5">
                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                        Sprint Goal Tracker
                      </h3>
                      <p className="text-[11px] text-[#94a3b8] mt-0.5">Focus: {selectedSprint}</p>
                    </div>
                    <span className="text-xs font-bold bg-blue-950 text-blue-400 px-2.5 py-1 rounded border border-blue-800">
                      10-Week Roadmap
                    </span>
                  </div>

                  {/* Sprints checklist card list */}
                  <div className="space-y-2.5">
                    {activeProject.blueprint?.sprintPlan ? (
                      activeProject.blueprint.sprintPlan
                        .find(s => s.name === selectedSprint)
                        ?.objectives.map((task, idx) => {
                          const status = taskStatuses[task] || "Todo";
                          return (
                            <div key={idx} className="p-3 bg-[#11192a]/30 border border-[#1e293b]/60 rounded-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-3 hover:border-slate-700 transition-colors">
                              <span className="text-xs font-bold text-white md:max-w-md">{task}</span>
                              
                              <div className="flex gap-1">
                                {["Todo", "In Progress", "Blocked", "Complete"].map((st) => {
                                  const isSel = status === st;
                                  return (
                                    <button
                                      key={st}
                                      onClick={() => handleTaskStatusChange(task, st as any)}
                                      className={`px-2 py-1 rounded text-[10px] font-bold border transition-all ${
                                        isSel
                                          ? st === "Complete" ? "bg-emerald-950/30 text-emerald-400 border-emerald-800" :
                                            st === "In Progress" ? "bg-blue-950/30 text-blue-400 border-blue-800" :
                                            st === "Blocked" ? "bg-red-950/30 text-red-400 border-red-800" :
                                            "bg-slate-900 text-slate-400 border-slate-700"
                                          : "bg-transparent text-slate-500 border-transparent hover:text-slate-300"
                                      }`}
                                    >
                                      {st}
                                    </button>
                                  );
                                })}
                              </div>
                            </div>
                          );
                        })
                    ) : (
                      <div className="text-center p-8 text-[#475569]">No roadmap sprint data populated yet in project blueprint.</div>
                    )}
                  </div>
                </div>
              )}

              {/* TAB 5: FUTURE INTEGRATIONS */}
              {activeCenterTab === "integrations" && (
                <div className="space-y-4">
                  <div className="p-4 bg-purple-950/10 border border-purple-900/40 rounded-xl">
                    <h3 className="text-xs font-black text-purple-400 flex items-center gap-1.5">
                      <Workflow className="w-4 h-4" />
                      Infrastructure Integration & Delivery Engine
                    </h3>
                    <p className="text-[11px] text-[#94a3b8] leading-relaxed mt-1">This layer provides clean, secure programmatic abstractions to hook your workspace directly to external repository endpoints and container fabrics. (Integrations ready for future activation).</p>
                  </div>

                  {/* Integration Cards */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {[
                      { name: "GitHub Repository Hook", desc: "Push code directly to your branch, sync issues", icon: Github, active: false, badge: "Abstraction Configured" },
                      { name: "Docker Container Fabric", desc: "Build images via compiled workspace Dockerfiles", icon: Monitor, active: false, badge: "Local Abstract Layer" },
                      { name: "Vercel Front-end Edge", desc: "Instantly route React/Vite SPA builds", icon: Zap, active: false, badge: "Abstracted API" },
                      { name: "Google Cloud Platform", desc: "Deploy server containers safely behind GCP Ingress", icon: Cpu, active: false, badge: "SDK Abstract" },
                    ].map((item, idx) => (
                      <div key={idx} className="p-3 bg-[#11192a]/40 border border-[#1e293b] rounded-xl flex items-start gap-3 relative overflow-hidden">
                        <item.icon className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-bold text-white">{item.name}</span>
                            <span className="text-[8px] uppercase px-1.5 py-0.5 bg-purple-950/50 text-purple-400 rounded-full border border-purple-900">{item.badge}</span>
                          </div>
                          <p className="text-[11px] text-[#94a3b8] mt-1 leading-normal">{item.desc}</p>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Architecture abstraction code */}
                  <div className="p-3.5 bg-[#0b0f19] border border-[#1e293b] rounded-xl mt-3">
                    <span className="text-[9px] uppercase font-bold text-[#475569] tracking-wider block mb-2">Clean Service Abstraction Interface</span>
                    <pre className="text-[10px] font-mono text-emerald-400 overflow-x-auto leading-relaxed max-h-40">
{`export interface CloudProviderService {
  connectRepo(repoUrl: string): Promise<{ success: boolean }>;
  triggerPipelineBuild(projectId: string): Promise<string>;
  provisionDatabaseInstance(schema: string): Promise<boolean>;
  getLiveDeploymentMetrics(): Promise<Record<string, number>>;
}`}
                    </pre>
                  </div>
                </div>
              )}

            </div>
          </div>

          {/* ========================================== */}
          {/* RIGHT PANEL: AI ASSISTANT (4 cols)         */}
          {/* ========================================== */}
          {showAiPanel && (
            <div className="lg:col-span-4 bg-[#0e1424]/75 border border-[#1e293b] rounded-xl flex flex-col h-full overflow-hidden shadow-2xl backdrop-blur-md">
            
            {/* AI Banner */}
            <div className="p-3 bg-[#11192a] border-b border-[#1e293b] flex items-center justify-between shrink-0">
              <span className="text-[10px] font-black uppercase tracking-wider text-white flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-blue-400 animate-pulse" />
                CTO Solutions Brain
              </span>
              <span className="text-[9px] uppercase bg-emerald-950/40 text-emerald-400 border border-emerald-900/60 px-1.5 py-0.5 rounded font-extrabold flex items-center gap-1">
                <span className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-ping" />
                Online
              </span>
            </div>

            {/* Quick Actions Panel (scrolling grid right below header) */}
            <div className="p-3 bg-[#141b2d]/30 border-b border-[#1e293b]/60 shrink-0">
              <span className="text-[9px] uppercase font-black text-[#475569] tracking-wider block mb-1.5">Quick Actions</span>
              <div className="grid grid-cols-2 gap-1.5 max-h-24 overflow-y-auto pr-1">
                {[
                  "Generate Component",
                  "Generate API",
                  "Generate Database Migration",
                  "Fix Bug",
                  "Explain Code",
                  "Optimize Performance",
                  "Generate Tests",
                  "Create Dockerfile",
                  "Generate README"
                ].map((action) => (
                  <button
                    key={action}
                    onClick={() => handleQuickAction(action)}
                    className="py-1 px-1.5 bg-[#1e293b]/60 hover:bg-blue-950/40 border border-[#334155]/60 hover:border-blue-800 text-[10px] text-slate-300 hover:text-white rounded text-left truncate font-medium transition-all"
                  >
                    🚀 {action}
                  </button>
                ))}
              </div>
            </div>

            {/* Chat Messages Log */}
            <div className="flex-1 overflow-y-auto p-3 space-y-3.5 custom-scrollbar bg-[#080c14]/40">
              {chatMessages.map((msg, i) => {
                const isAi = msg.role === "assistant";
                return (
                  <div key={i} className={`flex ${isAi ? "justify-start" : "justify-end"}`}>
                    <div className={`max-w-[85%] rounded-xl p-3 text-[11px] leading-relaxed relative ${
                      isAi 
                        ? "bg-[#11192a] text-slate-200 border border-[#1e293b]" 
                        : "bg-blue-600 text-white rounded-tr-none shadow-lg"
                    }`}>
                      <div className="flex justify-between items-center mb-1 text-[9px] font-bold text-[#475569] gap-4">
                        <span className={isAi ? "text-blue-400" : "text-blue-200"}>{isAi ? "CTO BRAIN" : "DEVELOPER"}</span>
                        <span>{msg.timestamp}</span>
                      </div>
                      <div className="whitespace-pre-wrap select-text">{msg.content}</div>
                    </div>
                  </div>
                );
              })}

              {isAiTyping && (
                <div className="flex justify-start">
                  <div className="bg-[#11192a] text-slate-300 border border-[#1e293b] rounded-xl p-3 text-[11px] flex items-center gap-2">
                    <Cpu className="w-3.5 h-3.5 animate-spin text-blue-400" />
                    <span className="italic animate-pulse">Compiling model completions...</span>
                  </div>
                </div>
              )}
              <div ref={chatBottomRef} />
            </div>

            {/* Suggested prompts pills row */}
            <div className="px-3 py-2 bg-[#11192a]/20 border-t border-[#1e293b]/40 overflow-x-auto whitespace-nowrap shrink-0 scrollbar-none flex gap-1.5">
              {[
                "Write sample schema",
                "Explain API logic",
                "List deployment needs",
                "Review project architecture"
              ].map((p, idx) => (
                <button
                  key={idx}
                  onClick={() => handleSendChatMessage(p)}
                  className="px-2 py-1 bg-[#141b2d] hover:bg-slate-800 border border-[#1e293b] rounded-full text-[10px] text-slate-400 hover:text-white transition-colors"
                >
                  💡 {p}
                </button>
              ))}
            </div>

            {/* Message input bar */}
            <div className="p-3 bg-[#11192a] border-t border-[#1e293b] shrink-0">
              <form 
                onSubmit={(e) => {
                  e.preventDefault();
                  handleSendChatMessage();
                }}
                className="flex items-center gap-2"
              >
                <input
                  type="text"
                  placeholder="Ask a technical layout question..."
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  className="flex-1 px-3 py-2 bg-[#080c14] border border-[#1e293b] rounded-lg text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
                />
                <button
                  type="submit"
                  disabled={!chatInput.trim() || isAiTyping}
                  className="p-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white rounded-lg transition-all"
                >
                  <Send className="w-3.5 h-3.5" />
                </button>
              </form>
            </div>
          </div>
          )}

        </div>
      )}

      {/* ========================================== */}
      {/* COMMAND PALETTE OVERLAY (CTRL+K)           */}
      {/* ========================================== */}
      <AnimatePresence>
        {showCommandPalette && (
          <div className="fixed inset-0 z-50 flex items-start justify-center pt-[15vh] px-4">
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowCommandPalette(false)}
              className="absolute inset-0 bg-black/60 backdrop-blur-sm"
            />

            {/* Modal Box */}
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: -20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: -20 }}
              className="w-full max-w-lg bg-[#11192a] border border-[#1e293b] rounded-xl shadow-2xl overflow-hidden z-10 flex flex-col text-left"
            >
              {/* Search line */}
              <div className="p-3 border-b border-[#1e293b] flex items-center gap-2.5 bg-[#0e1424]">
                <Search className="w-4 h-4 text-[#94a3b8] shrink-0" />
                <input
                  type="text"
                  autoFocus
                  placeholder="Search shortcuts and commands..."
                  value={cmdSearchQuery}
                  onChange={(e) => setCmdSearchQuery(e.target.value)}
                  className="flex-1 bg-transparent border-none text-xs text-white outline-none placeholder-slate-500"
                />
                <button 
                  onClick={() => setShowCommandPalette(false)}
                  className="text-slate-500 hover:text-white"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </div>

              {/* Suggestions list */}
              <div className="max-h-72 overflow-y-auto p-2 divide-y divide-[#1e293b]/40">
                {filteredCommands.length === 0 ? (
                  <div className="p-6 text-center text-xs text-[#475569]">No match for query found.</div>
                ) : (
                  filteredCommands.map((item, idx) => (
                    <button
                      key={idx}
                      onClick={() => executeCommand(item.name)}
                      className="w-full p-2.5 rounded-lg text-left flex justify-between items-center hover:bg-blue-950/20 text-slate-300 hover:text-white transition-all"
                    >
                      <div>
                        <p className="text-xs font-bold">{item.name}</p>
                        <p className="text-[10px] text-[#94a3b8] mt-0.5">{item.desc}</p>
                      </div>
                      <kbd className="px-1.5 py-0.5 bg-[#141b2d] border border-[#1e293b] rounded text-[9px] font-mono text-[#3b82f6]">
                        {item.shortcut}
                      </kbd>
                    </button>
                  ))
                )}
              </div>

              {/* Bottom bar */}
              <div className="p-2 bg-[#0e1424] border-t border-[#1e293b] flex justify-between items-center text-[9px] text-[#475569] px-4 select-none">
                <span>Use arrows to navigate, Esc to close</span>
                <span>AI Forge OS Command Line v1.0</span>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
}
